name: Docker Image CI

on:
  push:
    branches:  
    - main 
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:

  build_and_run:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./NeuralNetwork/ --file Dockerfile --tag vlado-nn-exercise:$(date +%s)
      
  
       
