name: Docker Image CI

on:
  workflow_dispatch:


jobs:

  build_and_run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./NeuralNetwork/Dockerfile --tag vlado-nn-exercise:$(date +%s)
      
  
       
